import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'leaflet/dist/leaflet.css';
import "../app/globals.css";
import { WorkSessionProvider } from "@/app/(admin)/-componentes/WorkSessionContext";
import WorkWidget from "@/components/workwidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zeit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 1. Envuelve todo el contenido con el Provider */}
        <WorkSessionProvider>
          
          {/* El contenido de tus páginas */}
          {children}
          
          {/* 2. Agrega el Widget aquí para que flote sobre cualquier página */}
          <WorkWidget />
          
        </WorkSessionProvider>
      </body>
    </html>
  );
}